services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    container_name: traefik
    cpus: 0.1
    mem_limit: 64m
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-letsencrypt:/letsencrypt

  gatus:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    container_name: gatus
    cpus: 0.2
    mem_limit: 64m
    extra_hosts:
      - "gatus.karkki.org:host-gateway"
    volumes:
      - ./gatus-config.yml:/config/config.yaml:ro
      - gatus-data:/data
    labels:
      traefik.enable: "true"
      traefik.http.routers.gatus.rule: Host(`gatus.karkki.org`)
      traefik.http.routers.gatus.entrypoints: websecure
      traefik.http.routers.gatus.tls.certresolver: letsencrypt
      traefik.http.services.gatus.loadbalancer.server.port: "8080"

volumes:
  traefik-letsencrypt:
    name: traefik-letsencrypt
  gatus-data:
