---
- name: Deploy services
  hosts: rpi5-01
  vars:
    get_cloudflare_ips_job: get-cloudflare-ips
    cloudflare_ips_env_file: ~/services/cloudflare-ips.env
  roles:
    - role: cloudflare-dns
      dns_records:
        - name: jellyfin.karkki.org
          ip_cmd: "$(curl ipinfo.io/ip)"
      proxied: true
    - role: cronjob
      job_name: "{{ get_cloudflare_ips_job }}" 
      job_script: "{{ playbook_dir }}/get-cloudflare-ips.sh"
      job_args: "{{ cloudflare_ips_env_file }}" 
      job_deps: curl
    - role: restic-backup
      restic_host: jellyfin
      restic_env_file: "{{ playbook_dir }}/secrets.env"
      restic_backup_dirs:
        - "~/shared/media/music"
        - "~/services/jellyfin-config"
  tasks:
    - name: Create data directories
      file:
        path: "{{ item }}"
        state: directory
      tags: [files]
      become: yes
      loop: []

    - name: Set data directory ownership
      file:
        path: "{{ item }}"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes
      tags: [files]
      become: yes
      loop: []

    - name: Create services directory
      file:
        path: "~/services"
        state: directory
      tags: [files, secrets, docker]

    - name: Decrypt and copy secrets
      copy:
        content: "{{ lookup('community.sops.sops', 'secrets.env') }}"
        dest: ~/.env
        mode: "0600"
      tags: [files, copy, secrets, docker]

    - name: Symlink secrets to services dir
      file:
        src: ~/.env
        dest: ~/services/.env
        state: link
        force: yes
      tags: [files, secrets, docker]

    - name: Set Cloudflare IPs changed fact
      ansible.builtin.set_fact:
        cloudflare_ips_changed: job_changed[get_cloudflare_ips_job]

    - name: Get Cloudflare IPs now
      ansible.builtin.shell:
        set -a; . ~/scripts/{{ get_cloudflare_ips_job }}.env; set +a;
        ~/scripts/{{ get_cloudflare_ips_job }}.sh
      when: job_changed[get_cloudflare_ips_job]
      changed_when: true

    - name: Copy docker compose file
      copy:
        src: docker-compose.yml
        dest: ~/services/docker-compose.yml
      tags: [docker, files, copy]

    - name: Start services
      tags: [docker]
      community.docker.docker_compose_v2:
        services:
          - traefik
          - jellyfin
        project_src: ~/services
        pull: always

    - name: Remove traefik container after DNS update
      community.docker.docker_container:
        name: traefik
        state: absent
      when: dns_changed | default(false)
      tags: [docker]

    - name: Remove traefik letsencrypt volume
      community.docker.docker_volume:
        name: traefik-letsencrypt
        state: absent
      when: dns_changed | default(false)
      tags: [docker]

    - name: Recreate traefik after DNS update
      community.docker.docker_compose_v2:
        project_src: ~/services
      when: dns_changed | default(false)
      tags: [docker]




