paperless:
  repository: "s3:https://fr9g5xx9nd3r.compat.objectstorage.eu-frankfurt-1.oraclecloud.com/karkkinet-paperless-backups"
  env:
    RESTIC_PASSWORD: "{{ .Env.RESTIC_PASSWORD }}"
    AWS_ACCESS_KEY_ID: "{{ .Env.AWS_ACCESS_KEY_ID }}"
    AWS_SECRET_ACCESS_KEY: "{{ .Env.AWS_SECRET_ACCESS_KEY }}"
  backup:
    schedule-permission: user_logged_on
    source:
      - /mnt/data/paperless/data
      - /mnt/data/paperless/media
    schedule: "*-*-* 03:00:00"
  retention:
    after-backup:
      keep-daily: 7
      keep-weekly: 4
      keep-monthly: 6
      prune: true
