---
- name: Validate
  ansible.builtin.assert:
    that:
      - cronjob_name | length > 0
      - cronjob_script | length > 0

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ [cronjob_deps] | flatten(levels=1) }}"

- name: Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
  loop:
    - ~/logs
    - ~/scripts

- name: Install script
  ansible.builtin.copy:
    src: "{{ cronjob_script }}"
    dest: "~/scripts/{{ cronjob_name }}.sh"
    mode: "0750"
  register: cronjob_script_result

- name: Decrypt and copy env file
  copy:
    content: "{{ lookup('community.sops.sops', cronjob_env_file) }}"
    dest: ~/scripts/{{ cronjob_name }}.env
    mode: "0600"
  tags: [files]
  no_log: true
  register: cronjob_env_result
  when: cronjob_env_file is not none

- name: Setup cron
  ansible.builtin.cron:
    name: "{{ cronjob_name }} {{ cronjob_args }}"
    minute: "{{ cronjob_minute | default('*') }}"
    hour: "{{ cronjob_hour | default('*') }}"
    day: "{{ cronjob_day | default('*') }}"
    job: >-
      set -a;
      [ -f ~/scripts/{{ cronjob_name }}.env ] && . ~/scripts/{{ cronjob_name }}.env;
      set +a;
      ~/scripts/{{ cronjob_name }}.sh {{ cronjob_args }}  >> ~/logs/{{ cronjob_name }}.log 2>&1
  register: cronjob_cron_result

- name: Setup log rotation
  become: yes
  copy:
    dest: /etc/logrotate.d/{{ cronjob_name }}
    content: |
      {{ ansible_facts.user_dir }}/logs/{{ cronjob_name }}.log {
          daily
          rotate 7
          compress
          missingok
          notifempty
          copytruncate
      }

- name: Record change status
  ansible.builtin.set_fact:
    cronjob_changed: >-
      {{ cronjob_changed | default({}) | combine({
          cronjob_name: (cronjob_changed[cronjob_name] | default(false))
                    or cronjob_script_result is changed
                    or cronjob_env_result is changed
                    or cronjob_cron_result is changed
        }) }}
