apiVersion: v1
kind: Namespace
metadata:
  name: bind9
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bind9-config
data:
  named.conf: |
    acl internal {
        127.0.0.1;
        ::1;
        192.168.1.0/24;
        172.21.0.1/32;
        2001:14ba:700e:c00::/64;
    };

    options {
        forwarders {
            1.1.1.1;
            8.8.8.8;
        };

        allow-query {
            internal;
        };
    };

    zone "home.karkki.org" {
        type master;
        file "/etc/bind/zone.conf";
        update-policy { grant tsig-key subdomain home.karkki.org. ANY; };
    };
  zone.conf: |
    $ORIGIN home.karkki.org.

    $TTL 2d

    @       IN      SOA     ns.home.karkki.org. admin@karkki.org. (
                            2025050721  ; serial
                            12h         ; refresh
                            15m         ; retry
                            3w          ; expire
                            2h          ; minimum ttl
                            )
                            NS      ns.home.karkki.org.

    ns              IN      A       192.168.1.222

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  labels:
    app: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: ubuntu/bind9:latest
          volumeMounts:
            - name: bind9-config
              mountPath: /etc/bind
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          env:
            - name: BIND9_USER
              value: "root"
            - name: TZ
              value: "Europe/Helsinki"
          volumes:
            - name: bind9-config
              configMap:
                name: bind9-config
                items:
                  - key: named.conf
                    path: named.conf
                  - key: zone.conf
                    path: zone.conf
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "bind9"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.222,2001:14ba:700e:0c00:1144:dcf2:fdb9:b676
spec:
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: bind9-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: bind9
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "bind9"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.222,2001:14ba:700e:0c00:1144:dcf2:fdb9:b676
spec:
  type: LoadBalancer
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: bind9-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: bind9
