apiVersion: v1
kind: Namespace
metadata:
  name: bind9
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bind9
  labels:
    app: bind9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bind9
  template:
    metadata:
      labels:
        app: bind9
    spec:
      containers:
        - name: bind9
          image: ubuntu/bind9:latest
          ports:
            - containerPort: 53
              protocol: TCP
            - containerPort: 53
              protocol: UDP
          env:
            - name: BIND9_USER
              value: "root"
            - name: TZ
              value: "Europe/Helsinki"
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: "bind9"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.222,2001:14ba:700e:0c00:1144:dcf2:fdb9:b676
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - ipv4
    - ipv6
  ports:
    - name: bind9-tcp
      protocol: TCP
      port: 53
      targetPort: 53
  selector:
    app: bind9
---
apiVersion: v1
kind: Service
metadata:
  name: bind9-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: "bind9"
    metallb.universe.tf/loadBalancerIPs: 192.168.1.222,2001:14ba:700e:0c00:1144:dcf2:fdb9:b676
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - ipv4
    - ipv6
  ports:
    - name: bind9-udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: bind9
