apiVersion: v1
kind: Secret
metadata:
    name: bw-auth-token
type: Opaque
stringData:
    auth-token: ENC[AES256_GCM,data:KWclkQgk2+S/G5rawzFtoIpy2rxXmTrvBcc71ngRhohylferQHgYh7DmuNHPgTI7Eog9n/asXWvZI/JtrRPlhzWNXY3gaz2wGpX/e9Wx7pIU4ALMFvdV2ySjt8sQKA==,iv:c5JQW9Z19PWLhYyVHvOzVjcFG/rvmSEpSp5z/iBn/oE=,tag:Vbhf3lLtVyH2r+gj0K/uSg==,type:str]
sops:
    lastmodified: "2025-05-25T10:19:34Z"
    mac: ENC[AES256_GCM,data:hpWu4r9nVWBDyGVu48HrvoY7YHWSstRyD2INgHbaPA1Td6lxO9t9l8y3NcBqmNDdWq7XESe/TuuaF1UTVWBzrH63tLua+jFVmBjDH3SzmW3Ef0Eq17lztU0oJvJYlVAPZKThQibCbQ3HbBw2Pt/J7RtSdD1y1p7EyfBAGs6lcS0=,iv:m9qTLZlDhQbpsCwFCLudiQop6gvsHCBe7aQOPYW4puo=,tag:YQ8R7ViqanyLn7WR7VNUQg==,type:str]
    pgp:
        - created_at: "2025-05-25T10:19:34Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA02SLRqLCdlOAQ/+OsPLSWmcCbRHyt+gc1/emyfXFzVUov7K1/8EvRwtkder
            7zqZDIZfTMYh6HLDzLAqQPqGodCPKFX9i3GEQaxOxf/YzXKdMcz2NYsBo7Xo8d9d
            BSwvTRrGydAe7L/193WPE40/9PizLEXZxLWHeafxnxCujEL/5EJWhcaYStwaSoCT
            ZdfBv0xtFMh+cRPDTEsTnwYSwpOkQXslAHnfbrlNCSVjNGig3MPmQ4xRX48Cz233
            4lkVEX0SoSu5KO7vfrHFYPrzbTxU1Cv6vd3MDnWeec/znbFoCMtEZGrJAAUd40yn
            9CtEyDo3Ex1xxagKmaVAGcSz53pwRyEEaAukQkj2LZvWEoY0yPIyhe+FVjYuDyq9
            4vXGIgV4sfNGvewSNzB+WeZrwKP0sTz+5AaofmQmBK8CDvw/o+YUhRotp4zIlJtw
            GLQi9ebrp43CSNQE3Qey6xgHe+gCxnsISIYY1mJleEAFrLBLjBdWgP68plKxZL3m
            redFKqEpJVdFUCmbB8hcvtMGvv+aWm6KOhxZcPJo08yyGUQ6U1H0xmls25bgpCGp
            AYf/qldHT3LdwFIp4apoJQoUVGpN0g2qit0o21wS17I0FiI0C0WPOkEeyvkFyoSY
            PnjLafGy/rzY69J8uupT+csDV2bsfPMYqg6dCq77abXl+BfA8fGArEPRyvezZyXS
            UQHjRIoBSmgjSRwHr+f9xSmNQL9ECwiDhhSr/sgU6OuyVvhx7jdQrgPyEX9lgC5C
            hUQUhn6vV117nCo4ek3EW+J9+HruA2aMOrHAmmRx/9Citg==
            =KAO6
            -----END PGP MESSAGE-----
          fp: 16faf2c055378d5b8f53f93958078e2903644c30 # pragma: allowlist secret
    encrypted_regex: ^(auth-token)$
    version: 3.10.2
