apiVersion: v1
kind: Secret
metadata:
    name: bw-auth-token
type: Opaque
stringData:
    auth-token: ENC[AES256_GCM,data:ymyD2hRjnNT9O/3c9MnpOaFExLQistA9iGrjxiinBdnYqA/zR5LIqiZ9I9ET1EKrE9jFp+ZvtIq1OochB3QD05ATvBc4GDzGX6NEQlPNwLND7eQ0Dx54MjF81SQMLQ==,iv:b9SaiZWh0ZbjGBeLBqKoRbN3Ln/ODFl8/XqoIjIbCuA=,tag:4twHd6pgByfcMfw8hWU64g==,type:str]
sops:
    age:
        - recipient: age1yj0hm72rhuad9v5g7wu0j75x6zrp8vfcpx929mfvqs7sh7zc3cqsl9tnln
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVGhqaEVSdGswTHpjMnpD
            ZWNHZmwzL1U1QU9MZFRrVFlqQ1BnUG1uL2xzCnNBTG14ZlBuWlYyeEtqRzgvRGlh
            b2NyRnVsS3RYNUtWVW5weDFJaXZMR1EKLS0tIFgySVQ3djI0TzFvMVFLR2dXNnFQ
            Ty9TeTFXUFBYWHdubmN6MjdFc2xBeUkKDQE7b2CCSuCZTXS7wCWQIGEpgQ5ltL0R
            aK16CMkO0Pmi6QypE+HPM/7BhthMx+JDINMA5s3UNfVYp+rA91ylUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-03T15:44:21Z"
    mac: ENC[AES256_GCM,data:ej7/jgccdNI7IaS7vvTRcIveWYaj2QyUN7cya6j9U83EVg1E4qCO9dfhQMoDbAsZmsw3jUOTWiXntdMpAzkbvY1So88yxdGQPKadsiMFLOBIIYEkTLLfGhSSF2YhhoTXBve9vyvP/tSUm/1Hoojvey47sgvR0CZBREBGwZjm2QM=,iv:HscQ+9YicbCi62rIbYmGZih+Q6jHd12I6vK0AomXB7Y=,tag:Iywno/8cpV+2kC9Rvg4dOg==,type:str]
    encrypted_regex: ^(auth-token)$
    version: 3.10.2
