apiVersion: v1
kind: Secret
metadata:
    name: bw-auth-token
type: Opaque
stringData:
    auth-token: ENC[AES256_GCM,data:1Ap2bzff+zoQZXIAa1/tBj5vja5WLwswESM1aZ9irHalBJjEjMQOBkAcRrQrZNychTPwL31BpZSyz4SYEfm64oNsg0jVBa8GnTtb0wI6LV3bS5pq4mqMq8GtTzHCfQ==,iv:fwHJGstKn6VhGt00q+GlWCkObVw25gu2gzWfJ/yzD6E=,tag:7ojjoB1FV63V77t0bsWz1Q==,type:str]
sops:
    age:
        - recipient: age17l2rn8v92h7nckxx60vvp8yt8slk8fut3gl5mfvnd5tyl7mkj5uq9t77ea
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMlJzNVNQMHRTdG1GWFYy
            anhHREQzZVJqd0J5UGRVWUVrZW04aTFaYWhnCjNLTk1HcjZOd1oybnQ5bjJta1ZY
            bThhZ3NBMndUQnB4aThjZHNkOHVDMkEKLS0tIEtNanZsTklVdmR5Z1ZwTkR0MW40
            czhSOW1QQW5kdndyMlpRYURGQldZMTQKlHNEpTAe4QETIm4Y6UPoZR2Hg0dX+i9M
            Q2KEJ+ssNT7Jr4lSHg/jWPgQUjRWHROoCLm7b4QobWXVbtpJLcDJ0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-08T12:34:01Z"
    mac: ENC[AES256_GCM,data:YyPPEK3u26MIZRq3hDdd62HDdczcUn+zpxp+2eCaK4BAdcMriiLr3YiPa+9L/TExIT1md1rNToWOsE4X62TyyMqCA6FsQ9df77jgMuJ6nR7BszYaFGyr/NcYvq2v1wlSxyMfDSrrl/7O2PhQmx0oZwdX0B3YO6s0Osi0m5f80T8=,iv:p7UmBIv8vPGNFZK+XoGDAhSx8zgk7+J/llsW8WUSvqs=,tag:eJ23j2iUICAo9K2IC1TxFg==,type:str]
    encrypted_regex: ^(auth-token)$
    version: 3.10.2
