apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1

  storage:
    size: 10Gi

  superuserSecret:
    name: postgresql-superuser

  postgresql:
    parameters:
      archive_timeout: "3600"
