---
- name: Wait for hosts to be reachable
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:

- name: Install k3s on server
  hosts: all
  tasks:
    - name: Wait for API server on VIP
      ansible.builtin.wait_for:
        host: "{{ k3s_vip }}"
        port: 6443
        timeout: 300
        state: started

    - name: Download k3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/get-k3s.sh
        mode: "0755"

    - name: Install k3s (join existing server)
      ansible.builtin.command:
        cmd: >
          /tmp/get-k3s.sh server
          --disable traefik --disable servicelb --flannel-iface eth0
          --server https://{{ k3s_vip }}:6443
          --token {{ k3s_token }}
        creates: /usr/local/bin/k3s-uninstall.sh

    - name: Start k3s on joined servers
      ansible.builtin.systemd:
        name: k3s
        state: started
        enabled: true
        daemon_reload: true
