apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: headlamp-tls
spec:
  secretName: headlamp-tls
  issuerRef:
    name: cloudflare-issuer
    kind: ClusterIssuer
  dnsNames:
    - headlamp.k8s.karkki.org
    - k8s.karkki.org
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-headlamp
spec:
  redirectRegex:
    regex: ^https?://k8s\.karkki\.org(.*)
    replacement: https://headlamp.k8s.karkki.org${1}
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`headlamp.k8s.karkki.org`)
      kind: Rule
      services:
        - name: headlamp
          port: 80
  tls:
    secretName: headlamp-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: headlamp-redirect
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`k8s.karkki.org`)
      kind: Rule
      middlewares:
        - name: redirect-to-headlamp
      services:
        - name: headlamp
          port: 80
  tls:
    secretName: headlamp-tls
