---
- name: Validate
  ansible.builtin.assert:
    that: 
      - restic_host | length > 0
      - restic_env_file | length > 0
      - restic_backup_dirs | length > 0

- name: Set facts
  set_fact:
    restic_backup_job: restic-backup-{{ restic_host }}
    restic_backup_script: "{{ role_path }}/files/restic-backup.sh"

- include_role: { name: cronjob }
  vars:
    cronjob_name: "{{ restic_backup_job }}"
    cronjob_script: "{{ restic_backup_script }}"
    cronjob_args: "{{ restic_host }} {{ restic_backup_dirs | join(' ') }}"
    cronjob_env_file: "{{ restic_env_file }}"
    cronjob_minute: "0"
    cronjob_hour: "{{ restic_backup_hour | default('3') }}"

