---
- name: Validate
  ansible.builtin.assert:
    that: 
      - restic_host | length > 0
      - restic_env_file | length > 0
      - restic_backup_dirs | length > 0

- name: Set facts
  set_fact:
    restic_backup_job: restic-backup-{{ restic_host }}
    restic_backup_script: "{{ role_path }}/files/restic-backup.sh"

- include_role: { name: cronjob }
  vars:
    job_name: "{{ restic_backup_job }}"
    job_script: "{{ restic_backup_script }}"
    job_args: "{{ restic_host }} {{ restic_backup_dirs | join(' ') }}" 
    job_env_file: "{{ restic_env_file }}"
    job_minute: "0"
    job_hour: "{{ restic_backup_hour | default('3') }}"

