apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: traefik
spec:
  interval: 1h
  url: https://helm.traefik.io/traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-crds
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik-crds
      version: 1.7.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
spec:
  interval: 1h
  chart:
    spec:
      chart: traefik
      version: 3.4.0
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
    ports:
      web:
        redirections:
          entrypoints:
            entryPoint:
              scheme: https
              permantent: true
              to: websecure
      websecure:
        tls:
          enabled: true
    service:
      spec:
        loadBalancerIP: 192.168.1.220
