apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-sm-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitwarden.com
    targetRevision: 1.1.0
    chart: sm-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: bitwarden
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
