apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare
spec:
  organizationId: "60ceb718-168e-4c92-acbc-b2dc012f1217"
  secretName: cloudflare # pragma: allowlist secret
  map:
    - bwSecretId: "d5a7351c-a839-49f5-a67f-b2dc0131528b"
      secretName: api-key # pragma: allowlist secret
    - bwSecretId: "08393544-bffb-420d-9aa5-b2dc01315f21"
      secretName: api-token # pragma: allowlist secret
  authToken:
    secretName: bw-auth-token # pragma: allowlist secret
    secretKey: token # pragma: allowlist secret
