---
- name: Set facts
  ansible.builtin.set_fact:
    update_dns_job: update-dns
    update_dns_script: "{{ role_path }}/files/update-dns.sh"
    update_dns_secrets: "{{ role_path }}/files/cloudflare-secrets.env"

- name: Install DNS update jobs
  ansible.builtin.include_role:
    name: cronjob
  vars:
    cronjob_name: "{{ update_dns_job }}"
    cronjob_script: "{{ update_dns_script }}"
    cronjob_env_file: "{{ update_dns_secrets }}"
    cronjob_deps: jq
    cronjob_args: "{{ rec.name }} {{ rec.ip_cmd }} {{ proxied | ternary('true','false') }}"
  loop: "{{ dns_records }}"
  loop_control:
    loop_var: rec
    label: "{{ rec.name }}"

- name: Set DNS changed fact
  ansible.builtin.set_fact:
    dns_changed: "{{ cronjob_changed[update_dns_job] | default(false) }}"

- name: Run DNS update now
  ansible.builtin.shell: >-
    set -a; . ~/scripts/{{ update_dns_job }}.env; set +a;
    ~/scripts/{{ update_dns_job }}.sh {{ item }}
  loop: "{{ update_dns_args }}"
  when: dns_changed
  changed_when: true

- name: Get Cloudflare IPs now
  ansible.builtin.shell:
    set -a; . ~/scripts/{{ get_cloudflare_ips_job }}.env; set +a;
    ~/scripts/{{ get_cloudflare_ips_job }}.sh
  when: dns_changed
  changed_when: true
