apiVersion: k8s.bitwarden.com/v1
kind: BitwardenSecret
metadata:
  name: cloudflare
spec:
  organizationId: "60ceb718-168e-4c92-acbc-b2dc012f1217"
  secretName: cloudflare # pragma: allowlist secret
  map:
    - bwSecretId: "d5a7351c-a839-49f5-a67f-b2dc0131528b"
      secretKeyName: api-key # pragma: allowlist secret
  authToken:
    secretName: bw-auth-token # pragma: allowlist secret
    secretKey: auth-token # pragma: allowlist secret
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloudflare@vjm.anonaddy.me
    privateKeySecretRef:
      name: cloudflare-issuer-key
    solvers:
      - dns01:
          cloudflare:
            email: cloudflare@vjm.anonaddy.me
            apiKeySecretRef:
              name: cloudflare
              key: api-key
