services:
  traefik:
    image: traefik:v3
    restart: unless-stopped
    command:
      - --log.level=INFO
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.dnschallenge=true
      - --certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.letsencrypt.acme.email=${ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
    environment:
      CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN}
    ports:
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data/traefik/letsencrypt:/letsencrypt

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - redis
    cpus: 0.8
    mem_limit: 768m
    volumes:
      - /mnt/data/paperless/data:/usr/src/paperless/data
      - /mnt/data/paperless/media:/usr/src/paperless/media
      - /mnt/data/paperless/export:/usr/src/paperless/export
      - /mnt/data/paperless/consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_URL: https://paperless.karkki.org
      PAPERLESS_REDIS: redis://redis:6379
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_OCR_LANGUAGE: eng
      PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_TIME_ZONE: Europe/Helsinki
    labels:
      traefik.enable: "true"
      traefik.http.routers.paperless.rule: Host(`paperless.karkki.org`)
      traefik.http.routers.paperless.entrypoints: websecure
      traefik.http.routers.paperless.tls.certresolver: letsencrypt
      traefik.http.services.paperless.loadbalancer.server.port: "8000"

  redis:
    image: redis:7
    restart: unless-stopped
    cpus: 0.1
    mem_limit: 64m
    volumes:
      - /mnt/data/paperless/redis:/data
