apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.19.2
      chart: cert-manager
      helm:
        values: |
          crds:
            enabled: true
    - repoURL: https://github.com/vjrasane/infra.git
      targetRevision: HEAD
      path: cert-manager
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
