apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg-system
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: https://cloudnative-pg.github.io/charts
      targetRevision: 0.23.0
      chart: cloudnative-pg
    - repoURL: https://github.com/vjrasane/infra.git
      targetRevision: HEAD
      path: cnpg-system
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Replace=true
