apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: samba
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://geek-cookbook.github.io/charts/
      targetRevision: 6.2.2
      chart: samba
      helm:
        values: |
          env:
            TZ: Europe/Helsinki
            SAMBA_HOSTS_ALLOW: 100.0.0.0/8 192.168.0.0/16 10.0.0.0/8 172.16.0.0/12

          service:
            main:
              type: LoadBalancer
              ports:
                tcp:
                  enabled: true
                  port: 445
                netbios:
                  enabled: false

          persistence:
            media:
              enabled: true
              type: hostPath
              hostPath: /mnt/ssd1/smb
              mountPath: /share/media

          configmap:
            config:
              enabled: true
              data:
                config.yml: |
                  auth:
                    - user: media
                      group: media
                      uid: 1000
                      gid: 1000
                      password: changeme

                  global:
                    - "force user = media"
                    - "force group = media"

                  share:
                    - name: media
                      path: /share/media
                      browsable: yes
                      readonly: no
                      guestok: no
                      validusers: media
                      writelist: media
                      veto: no
    - repoURL: https://github.com/vjrasane/infra.git
      targetRevision: HEAD
      path: samba
  destination:
    server: https://kubernetes.default.svc
    namespace: samba
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
