---
- name: Wait for hosts to be reachable
  hosts: all
  gather_facts: false
  pre_tasks:
    - name: Wait for SSH
      ansible.builtin.wait_for_connection:

- name: Configure LXC containers
  hosts: all
  tasks:
    - name: Install packages
      ansible.builtin.package:
        name:
          - nfs-common
          - open-iscsi
          - cryptsetup
        state: present
        update_cache: true

    - name: Create conf-kmsg.sh file
      ansible.builtin.template:
        src: conf-kmsg.sh.j2
        dest: /usr/local/bin/conf-kmsg.sh
        owner: root
        group: root
        mode: "0755"

    - name: Create service conf
      ansible.builtin.template:
        src: conf-kmsg.service.j2
        dest: /etc/systemd/system/conf-kmsg.service
        owner: root
        group: root
        mode: '0755'

    - name: Enable kmsg service
      ansible.builtin.service:
        name: conf-kmsg
        enabled: true
        state: started
      notify: reboot server

    - name: Enable iscsid service
      ansible.builtin.service:
        name: iscsid
        enabled: true
        state: started
      notify: reboot server

  handlers:
    - name: Reboot server
      become: true
      ansible.builtin.reboot:
      listen: reboot server
