// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface CrowdsecProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: Values;
}

export class Crowdsec extends Construct {
  public constructor(scope: Construct, id: string, props: CrowdsecProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_Values(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'crowdsec',
      repo: 'https://crowdsecurity.github.io/helm-charts',
      version: '0.22.0',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema values
 */
export interface Values {
  /**
   * @schema values#agent
   */
  readonly agent: Agent;

  /**
   * @schema values#config
   */
  readonly config: Config;

  /**
   * @schema values#lapi
   */
  readonly lapi: Lapi;

  /**
   * @schema values#container_runtime
   */
  readonly containerRuntime: ContainerRuntime;

  /**
   * @schema values#image
   */
  readonly image: Image;
}

/**
 * Converts an object of type 'Values' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Values(obj: Values | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'agent': toJson_Agent(obj.agent),
    'config': toJson_Config(obj.config),
    'lapi': toJson_Lapi(obj.lapi),
    'container_runtime': obj.containerRuntime,
    'image': toJson_Image(obj.image),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema Agent
 */
export interface Agent {
  /**
   * @schema Agent#enabled
   */
  readonly enabled?: boolean;

  /**
   * Optional, the serviceAccountName used in the deployment.
   *
   * @schema Agent#serviceAccountName
   */
  readonly serviceAccountName?: string;

  /**
   * @schema Agent#acquisition
   */
  readonly acquisition: Acquisition[];

  /**
   * @schema Agent#additionalAcquisition
   */
  readonly additionalAcquisition?: any[];
}

/**
 * Converts an object of type 'Agent' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Agent(obj: Agent | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enabled': obj.enabled,
    'serviceAccountName': obj.serviceAccountName,
    'acquisition': obj.acquisition?.map(y => toJson_Acquisition(y)),
    'additionalAcquisition': obj.additionalAcquisition?.map(y => y),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema Config
 */
export interface Config {
  /**
   * @schema Config#parsers
   */
  readonly parsers?: any;

  /**
   * @schema Config#scenarios
   */
  readonly scenarios?: any;

  /**
   * @schema Config#postoverflows
   */
  readonly postoverflows?: any;

  /**
   * @schema Config#profiles.yaml
   */
  readonly profilesYaml?: string;

  /**
   * @schema Config#notifications
   */
  readonly notifications?: any;

  /**
   * @schema Config#simulation.yaml
   */
  readonly simulationYaml?: string;

  /**
   * @schema Config#console.yaml
   */
  readonly consoleYaml?: string;

  /**
   * @schema Config#capi_whitelists.yaml
   */
  readonly capiWhitelistsYaml?: string;

  /**
   * @schema Config#config.yaml.local
   */
  readonly configYamlLocal?: string;

  /**
   * @schema Config#agent_config.yaml.local
   */
  readonly agentConfigYamlLocal?: string;

  /**
   * @schema Config#appsec_config.yaml.local
   */
  readonly appsecConfigYamlLocal?: string;
}

/**
 * Converts an object of type 'Config' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Config(obj: Config | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'parsers': obj.parsers,
    'scenarios': obj.scenarios,
    'postoverflows': obj.postoverflows,
    'profiles.yaml': obj.profilesYaml,
    'notifications': obj.notifications,
    'simulation.yaml': obj.simulationYaml,
    'console.yaml': obj.consoleYaml,
    'capi_whitelists.yaml': obj.capiWhitelistsYaml,
    'config.yaml.local': obj.configYamlLocal,
    'agent_config.yaml.local': obj.agentConfigYamlLocal,
    'appsec_config.yaml.local': obj.appsecConfigYamlLocal,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema Lapi
 */
export interface Lapi {
  /**
   * @schema Lapi#enabled
   */
  readonly enabled?: boolean;
}

/**
 * Converts an object of type 'Lapi' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Lapi(obj: Lapi | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'enabled': obj.enabled,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema containerRuntime
 */
export enum ContainerRuntime {
  /** docker */
  DOCKER = "docker",
  /** containerd */
  CONTAINERD = "containerd",
}

/**
 * @schema image
 */
export interface Image {
  /**
   * @schema image#repository
   */
  readonly repository: string;

  /**
   * @schema image#tag
   */
  readonly tag?: string;

  /**
   * @schema image#pullPolicy
   */
  readonly pullPolicy: string;
}

/**
 * Converts an object of type 'Image' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Image(obj: Image | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'repository': obj.repository,
    'tag': obj.tag,
    'pullPolicy': obj.pullPolicy,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema Acquisition
 */
export interface Acquisition {
  /**
   * @schema Acquisition#namespace
   */
  readonly namespace: string;

  /**
   * @schema Acquisition#podName
   */
  readonly podName: string;

  /**
   * @schema Acquisition#program
   */
  readonly program: string;

  /**
   * @schema Acquisition#poll_without_inotify
   */
  readonly pollWithoutInotify?: boolean;
}

/**
 * Converts an object of type 'Acquisition' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_Acquisition(obj: Acquisition | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'namespace': obj.namespace,
    'podName': obj.podName,
    'program': obj.program,
    'poll_without_inotify': obj.pollWithoutInotify,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
