// generated by cdk8s
import { ApiObject, ApiObjectMetadata, GroupVersionKind } from 'cdk8s';
import { Construct } from 'constructs';


/**
 * HelmChartConfig represents additional configuration for the installation of Helm chart release.
This resource is intended for use when additional configuration needs to be passed to a HelmChart
that is managed by an external system.
 *
 * @schema HelmChartConfig
 */
export class HelmChartConfig extends ApiObject {
  /**
   * Returns the apiVersion and kind for "HelmChartConfig"
   */
  public static readonly GVK: GroupVersionKind = {
    apiVersion: 'helm.cattle.io/v1',
    kind: 'HelmChartConfig',
  }

  /**
   * Renders a Kubernetes manifest for "HelmChartConfig".
   *
   * This can be used to inline resource manifests inside other objects (e.g. as templates).
   *
   * @param props initialization props
   */
  public static manifest(props: HelmChartConfigProps = {}): any {
    return {
      ...HelmChartConfig.GVK,
      ...toJson_HelmChartConfigProps(props),
    };
  }

  /**
   * Defines a "HelmChartConfig" API object
   * @param scope the scope in which to define this object
   * @param id a scope-local name for the object
   * @param props initialization props
   */
  public constructor(scope: Construct, id: string, props: HelmChartConfigProps = {}) {
    super(scope, id, {
      ...HelmChartConfig.GVK,
      ...props,
    });
  }

  /**
   * Renders the object to Kubernetes JSON.
   */
  public override toJson(): any {
    const resolved = super.toJson();

    return {
      ...HelmChartConfig.GVK,
      ...toJson_HelmChartConfigProps(resolved),
    };
  }
}

/**
 * HelmChartConfig represents additional configuration for the installation of Helm chart release.
 * This resource is intended for use when additional configuration needs to be passed to a HelmChart
 * that is managed by an external system.
 *
 * @schema HelmChartConfig
 */
export interface HelmChartConfigProps {
  /**
   * @schema HelmChartConfig#metadata
   */
  readonly metadata?: ApiObjectMetadata;

  /**
   * HelmChartConfigSpec represents additional user-configurable details of an installed and configured Helm chart release.
   * These fields are merged with or override the corresponding fields on the related HelmChart resource.
   *
   * @schema HelmChartConfig#spec
   */
  readonly spec?: HelmChartConfigSpec;
}

/**
 * Converts an object of type 'HelmChartConfigProps' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_HelmChartConfigProps(obj: HelmChartConfigProps | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'metadata': obj.metadata,
    'spec': toJson_HelmChartConfigSpec(obj.spec),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * HelmChartConfigSpec represents additional user-configurable details of an installed and configured Helm chart release.
 * These fields are merged with or override the corresponding fields on the related HelmChart resource.
 *
 * @schema HelmChartConfigSpec
 */
export interface HelmChartConfigSpec {
  /**
   * Configures handling of failed chart installation or upgrades.
   * - `reinstall` will perform a clean uninstall and reinstall of the chart.
   * - `abort` will take no action and leave the chart in a failed state so that the administrator can manually resolve the error.
   *
   * @schema HelmChartConfigSpec#failurePolicy
   */
  readonly failurePolicy?: HelmChartConfigSpecFailurePolicy;

  /**
   * Override complex Chart values via inline YAML content.
   * Helm CLI positional argument/flag: `--values`
   *
   * @schema HelmChartConfigSpec#valuesContent
   */
  readonly valuesContent?: string;

  /**
   * Override complex Chart values via references to external Secrets.
   * Helm CLI positional argument/flag: `--values`
   *
   * @schema HelmChartConfigSpec#valuesSecrets
   */
  readonly valuesSecrets?: HelmChartConfigSpecValuesSecrets[];
}

/**
 * Converts an object of type 'HelmChartConfigSpec' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_HelmChartConfigSpec(obj: HelmChartConfigSpec | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'failurePolicy': obj.failurePolicy,
    'valuesContent': obj.valuesContent,
    'valuesSecrets': obj.valuesSecrets?.map(y => toJson_HelmChartConfigSpecValuesSecrets(y)),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * Configures handling of failed chart installation or upgrades.
 * - `reinstall` will perform a clean uninstall and reinstall of the chart.
 * - `abort` will take no action and leave the chart in a failed state so that the administrator can manually resolve the error.
 *
 * @schema HelmChartConfigSpecFailurePolicy
 */
export enum HelmChartConfigSpecFailurePolicy {
  /** abort */
  ABORT = "abort",
  /** reinstall */
  REINSTALL = "reinstall",
}

/**
 * SecretSpec describes a key in a secret to load chart values from.
 *
 * @schema HelmChartConfigSpecValuesSecrets
 */
export interface HelmChartConfigSpecValuesSecrets {
  /**
   * Ignore changes to the secret, and mark the secret as optional.
   * By default, the secret must exist, and changes to the secret will trigger an upgrade of the chart to apply the updated values.
   * If `ignoreUpdates` is true, the secret is optional, and changes to the secret will not trigger an upgrade of the chart.
   *
   * @schema HelmChartConfigSpecValuesSecrets#ignoreUpdates
   */
  readonly ignoreUpdates?: boolean;

  /**
   * Keys to read values content from. If no keys are specified, the secret is not used.
   *
   * @schema HelmChartConfigSpecValuesSecrets#keys
   */
  readonly keys?: string[];

  /**
   * Name of the secret. Must be in the same namespace as the HelmChart resource.
   *
   * @schema HelmChartConfigSpecValuesSecrets#name
   */
  readonly name?: string;
}

/**
 * Converts an object of type 'HelmChartConfigSpecValuesSecrets' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_HelmChartConfigSpecValuesSecrets(obj: HelmChartConfigSpecValuesSecrets | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'ignoreUpdates': obj.ignoreUpdates,
    'keys': obj.keys?.map(y => y),
    'name': obj.name,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
