// generated by cdk8s
import { Helm, HelmProps } from 'cdk8s';
import { Construct } from 'constructs';

export interface LokiProps {
  readonly namespace?: string;
  readonly releaseName?: string;
  readonly helmExecutable?: string;
  readonly helmFlags?: string[];
  readonly values?: LokiValues;
}

export class Loki extends Construct {
  public constructor(scope: Construct, id: string, props: LokiProps = {}) {
    super(scope, id);
    let updatedProps = {};

    if (props.values) {
      const values = toJson_LokiValues(props.values);
      if (values) {
        const { additionalValues, ...valuesWithoutAdditionalValues } = values;
        updatedProps = {
          ...props,
          values: {
            ...this.flattenAdditionalValues(valuesWithoutAdditionalValues),
            ...additionalValues,
          },
        };
      }
    }

    const finalProps: HelmProps = {
      chart: 'loki',
      repo: 'https://grafana.github.io/helm-charts',
      version: '6.51.0',
      ...(Object.keys(updatedProps).length !== 0 ? updatedProps : props),
    };

    new Helm(this, 'Helm', finalProps);
  }

  private flattenAdditionalValues(props: { [key: string]: any }): { [key: string]: any } {
    for (let prop in props) {
      if (Array.isArray(props[prop])) {
        props[prop].map((item: any) => {
          if (typeof item === 'object' && prop !== 'additionalValues') {
            return this.flattenAdditionalValues(item);
          }
          return item;
        });
      }
      else if (typeof props[prop] === 'object' && prop !== 'additionalValues') {
        props[prop] = this.flattenAdditionalValues(props[prop]);
      }
    }

    const { additionalValues, ...valuesWithoutAdditionalValues } = props;

    return {
      ...valuesWithoutAdditionalValues,
      ...additionalValues,
    };
  }
}

/**
 * @schema loki
 */
export interface LokiValues {
  /**
   * @schema loki#loki
   */
  readonly loki?: LokiLoki;

  /**
   * @schema loki#minio
   */
  readonly minio?: { [key: string]: any };

  /**
   * @schema loki#grafana-agent-operator
   */
  readonly grafanaAgentOperator?: { [key: string]: any };

  /**
   * @schema loki#rollout-operator
   */
  readonly rolloutOperator?: { [key: string]: any };

  /**
   * @schema loki#global
   */
  readonly global?: { [key: string]: any };

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema loki#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'LokiValues' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_LokiValues(obj: LokiValues | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'loki': toJson_LokiLoki(obj.loki),
    'minio': ((obj.minio) === undefined) ? undefined : (Object.entries(obj.minio).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'grafana-agent-operator': ((obj.grafanaAgentOperator) === undefined) ? undefined : (Object.entries(obj.grafanaAgentOperator).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'rollout-operator': ((obj.rolloutOperator) === undefined) ? undefined : (Object.entries(obj.rolloutOperator).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'global': ((obj.global) === undefined) ? undefined : (Object.entries(obj.global).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema LokiLoki
 */
export interface LokiLoki {
  /**
   * @schema LokiLoki#rulerConfig
   */
  readonly rulerConfig?: LokiLokiRulerConfig;

  /**
   * Values that are not available in values.schema.json will not be code generated. You can add such values to this property.
   *
   * @schema LokiLoki#additionalValues
   */
  readonly additionalValues?: { [key: string]: any };
}

/**
 * Converts an object of type 'LokiLoki' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_LokiLoki(obj: LokiLoki | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'rulerConfig': toJson_LokiLokiRulerConfig(obj.rulerConfig),
    'additionalValues': ((obj.additionalValues) === undefined) ? undefined : (Object.entries(obj.additionalValues).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {})),
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */

/**
 * @schema LokiLokiRulerConfig
 */
export interface LokiLokiRulerConfig {
  /**
   * @schema LokiLokiRulerConfig#storage
   */
  readonly storage?: any;
}

/**
 * Converts an object of type 'LokiLokiRulerConfig' to JSON representation.
 */
/* eslint-disable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
export function toJson_LokiLokiRulerConfig(obj: LokiLokiRulerConfig | undefined): Record<string, any> | undefined {
  if (obj === undefined) { return undefined; }
  const result = {
    'storage': obj.storage,
  };
  // filter undefined values
  return Object.entries(result).reduce((r, i) => (i[1] === undefined) ? r : ({ ...r, [i[0]]: i[1] }), {});
}
/* eslint-enable max-len, @stylistic/max-len, quote-props, @stylistic/quote-props */
