apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: bitwarden
  namespace: sm-operator-system
spec:
  interval: 1h
  chart:
    spec:
      chart: bitwarden/sm-operator
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: bitwarden
        namespace: flux-system
  values:
    bwSecretsManagerRefreshInterval: 180
    cloudRegion: EU
